[tool.poetry]
name = "gpt2"
version = "0.1.0"
description = ""
authors = ["Satyam Tiwary <satyam@technoculture.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
